package org.example.fieldreserve.model;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

//Student Name: Araz Hafez
//ID: 433006827

@Entity
@Table(name = "fields") //create a table called "fields" in our database
public class Field {
    //This is going to be our primary key:
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer fieldID; //Every Field will be identified with a unique ID --> will be generated by database

    private String fieldName; //Every Field has a name, whether it is in a school, stadium etc
    private String fieldLocation; //The location of the specific field
    private double hourlyRate; //Hourly rate; varies for different fields
    private String availabilityStatus; //This shows whether the field is still available or not
    //added 2 new attributes:
    private String fieldType;
    private int capacity;

    @ManyToOne
    @JoinColumn(name = "location_id")
    private Location location;

    //Default-Non arg constructor
    public Field() {}

    //Parameterized Constructor --> updated this without fieldID because it will be generated by database
    public Field(String fieldName, String fieldLocation, double hourlyRate, String availabilityStatus){
        this.fieldName=fieldName;
        this.fieldLocation=fieldLocation;
        this.hourlyRate=hourlyRate;
        this.availabilityStatus=availabilityStatus;
    }

    //Getters and Setters
    public Integer getFieldID() {return fieldID;} //we only need getter for this, removed the setter

    public String getFieldName() {return fieldName;}
    public void setFieldName(String fieldName) {this.fieldName = fieldName;}

    public String getFieldLocation() {return fieldLocation;}
    public void setFieldLocation(String fieldLocation) {this.fieldLocation = fieldLocation;}

    public double getHourlyRate() {return hourlyRate;}
    public void setHourlyRate(double hourlyRate) {this.hourlyRate = hourlyRate;}

    public String getAvailabilityStatus() {return availabilityStatus;}
    public void setAvailabilityStatus(String availabilityStatus) {this.availabilityStatus = availabilityStatus;}

    public String getFieldType() {return fieldType;}
    public void setFieldType(String fieldType) {this.fieldType = fieldType;}

    public int getCapacity() {return capacity;}
    public void setCapacity(int capacity) {this.capacity = capacity;}

    public Location getLocation() {return location;}
    public void setLocation(Location location) {this.location = location;}

    public String getLocationCity() {
        if (location != null) {
            return location.getCity(); //Mohammad Adil can you check this***
        } else {
            return null;
        }
    }

    //Additional Methods

    //Function to check if field is available
    public boolean isAvailable() {
        return "AVAILABLE".equalsIgnoreCase(availabilityStatus);
    }

    //Function to book a field
    public void reserveField() {
        if (isAvailable()) {
            availabilityStatus = "BOOKED";
        }
    }

    //Function to free the field (After a booking is done or cancelled)
    public void releaseField() {
        availabilityStatus = "AVAILABLE";
    }

    //Function to calculate cost for X hours
    public double calculateCost(int hours) {
        return hourlyRate * hours;
    }

    //Function to display field info
    public String getFieldInfo() {
        return "Field: " + fieldName +
                ", Location: " + fieldLocation +
                ", Hourly Rate: AED" + hourlyRate +
                ", Available: " + availabilityStatus;
    }

    //Additional: toString method
    @Override
    public String toString() {
        return "Field: " + fieldName +
                ", Location: " + fieldLocation +
                ", Hourly Rate: AED" + hourlyRate +
                ", Available: " + availabilityStatus;
    }
}